#!/usr/bin/env bash

set -euo pipefail

[[ "$(uname)" == "Darwin" && "$(uname -m)" == "arm64" ]] || exit 1

command -v orb >/dev/null 2>&1 || exit 1

defaults write -g ApplePressAndHoldEnabled -bool false
defaults write -g InitialKeyRepeat -int 10
defaults write -g KeyRepeat -int 1
defaults write com.apple.dock persistent-apps -array

mkdir -p $HOME/Library/Application\ Support/com.mitchellh.ghostty
cat <<EOF > /Users/z/Library/Application\ Support/com.mitchellh.ghostty/config
font-family                   = Iosevka SS03
font-size                     = 20
font-feature                  = -liga, -calt, -dlig
window-padding-x              = 0
window-padding-y              = 0
confirm-close-surface         = false
macos-window-shadow           = false
adjust-cursor-thickness       = 50%
maximize                      = true
mouse-hide-while-typing       = true
quit-after-last-window-closed = true
window-decoration             = false
window-padding-balance        = true
palette                       = 0=#000000
palette                       = 1=#cc0403
palette                       = 2=#19cb00
palette                       = 3=#cecb00
palette                       = 4=#0d73cc
palette                       = 5=#cb1ed1
palette                       = 6=#0dcdcd
palette                       = 7=#c0caf5
palette                       = 8=#767676
palette                       = 9=#f2201f
palette                       = 10=#23fd00
palette                       = 11=#fffd00
palette                       = 12=#1a8fff
palette                       = 13=#fd28ff
palette                       = 14=#14ffff
palette                       = 15=#c0caf5
background                    = #000000
foreground                    = #c0caf5
cursor-color                  = #c0caf5
term                          = xterm-256color
command                       = /Applications/OrbStack.app/Contents/MacOS/bin/orb -w /home/z
EOF

touch $HOME/.hushlogin

orb info zx >/dev/null 2>&1 || orb create -u z nixos:unstable zx

orb -m zx -u root bash -c "
mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
ssh-keygen -F github.com || ssh-keyscan github.com >> ~/.ssh/known_hosts

ssh-add /home/z/.ssh/id_ed25519

NIX_CONFIG='extra-trusted-public-keys = nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
extra-substituters = https://nix-community.cachix.org
experimental-features = nix-command flakes' nix-shell -p git --run '
[ ! -d /home/z/src/zx ] && git clone git@github.com:tnxz/zx /home/z/src/zx
nixos-rebuild switch --flake /home/z/src/zx#zx --impure'

chown -R z:users /home/z/src
"
